export default {
  currentCategory: {},
  categories: [],
  products: [],
  brands: [],
  currentBrand: {},
  currentPrice: {},
  searchProductNameValue: "",
  productWithDetails: {},
  images: [],
  currentImage: {},
  firstImage: {},
  registerResponse: {},
  loginResponse: {},
  user: {},
  updatedUser:{},
  basket:{},
  basketResponse:{},
  totalPriceResponse:{}
};
